### PR TITLE
Fixing Bug: camel style for 'keys' and 'newImage' fileds don't work

### PR DESCRIPTION
**Pull request by cuongquay**
The detected keys are Pascal style with `Keys` and `NewImage`

### CODE REVIEW

**Comment by marcosnils** [comment]
@cuongquay we came across this problem also. The thing is that logstash-input-dynamodb plugin already handles keys like this, that's why we had to do it this way. 

https://github.com/awslabs/logstash-input-dynamodb/blob/ea61107ac2f270b024a8b1f28566b4fa946bb8f7/lib/logstash/inputs/DynamoDBLogParser.rb#L63

In fact, all keys inside the `dynamodb` hash are PascalCase, not only Keys and NewImage

**Comment by marcosnils** [comment]
@cuongquay shall we close this?

**Comment by cuongquay** [comment]
I have no idea. Currently I patch the source code by my own to make it works.
I just suppose the libraries should work in the real scenario. 

This is my code:

```
ENV PATH /opt/logstash/vendor/jruby/bin/:$PATH
RUN gem install logstash-input-dynamodb:'> 2' logstash-filter-dynamodb:'> 2'
RUN plugin install logstash-input-dynamodb logstash-filter-dynamodb

# Patch with local file by replacing the original file with Docker VOLUME
VOLUME /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-dynamodb-2.0.1/lib
```

And this is my conf

```
input { 
    dynamodb { 
        endpoint => "dynamodb.ap-northeast-1.amazonaws.com" 
        streams_endpoint => "streams.dynamodb.ap-northeast-1.amazonaws.com" 
        view_type => "new_and_old_images" 
        aws_access_key_id => "myid" 
        aws_secret_access_key => "mykey" 
        table_name => "mytable"
    } 
}
filter {
    dynamodb {          
    }
    mutate {
        remove_field => [ "topic", "message", "eventName" ]
    }
}
output { 
    elasticsearch { 
        hosts => "127.0.0.1:9200"
        index => "myindex"
        document_type => "mytype"
    } 
    stdout { } 
}
```

**Comment by marcosnils** [comment]
I believe the problem you're getting is because I've updated the input plugin accidentally and forgot to revert.

**Comment by marcosnils** [comment]
@cuongquay can you reinstall your logstash-input-dynamodb plugin and try again?. You should have the version 2.0.5. I accidentally updated the gem to 2.0.6 which caused this issue

**Comment by cuongquay** [comment]
Ok I got it

**Pull request closed without merging**
